apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ${AWS_PROJECT_NAME}
  region: ${AWS_REGION}
  version: "1.21"
availabilityZones:
- ${AWS_REGION}a
- ${AWS_REGION}b
privateCluster:
  enabled: false
vpc:
  nat:
    gateway: HighlyAvailable
iam:
  withOIDC: true
managedNodeGroups:
  - name: managed-1
    amiFamily: AmazonLinux2
    minSize: 2
    maxSize: 5
    volumeSize: 20
    instanceTypes:
    - "t3.small"
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        certManager: true
        cloudWatch: true
        ebs: true
